name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        engine: [used]
        include:
          - engine: used
            other: 123
          - engine: make-me-ghost # comment me out or add to engine axis
            other: 321

    steps:
      - run: echo Done ${{ matrix.other }}


  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        engine: [used]
        include:
          - engine: used
            other: 123

    steps:
      - run: echo Done ${{ matrix.other }}
